Update Jenkinsfile_AIP

diff --git a/Jenkinsfile_AIP b/Jenkinsfile_AIP
--- a/Jenkinsfile_AIP
+++ b/Jenkinsfile_AIP
@@ -51,6 +51,10 @@ spec:
 		HOSTS_DEV_DEPLOY=getDevDeployEnv()
 		USERNAME_RELEASE='muleadmin'
 		HOSTS_RELEASE_DEPLOY=getReleaseDeployEnv()
+		uri='http://pwwsftapp01/executionmanager/api'
+		username='devopsengineering@signetjewelers.com'
+		RequestID='779'
+		stage_name='dev3'
 	}
 	stages {
 		stage('Build & Unit Test') {
@@ -161,6 +165,56 @@ spec:
 			}
 		}
 	}
+}
+	stage('Post Deploy Tests') {
+		parallel {
+			stage('Smoke Test') {
+				steps {
+					echo "I am executing Smoke Test on target dev environment post deployment"
+				}
+				/*RESP=`curl -X GET "${uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
+				echo "The response for current execution status is: $RESP"
+				if [ "$RESP" != "[]" ];
+				then
+				echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
+				exit 1
+				else
+				echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
+				fi
+				# To abort the request before attempting to re-run, uncomment and run below line.
+				# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${RequestID}" ${uri}/Request/${RequestID}/abort/)
+				guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${stage_name}}" -H "id: ${RequestID}" ${uri}/ExecuteRequest/ | tr -d \")
+				echo "The GUID is: $guid"
+				status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+				echo "The status is: $status"
+				while [[ $status != *"Completed"* ]]
+				do
+				status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+				echo "The status is: $status"
+				sleep 15
+				done
+				status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${uri}/ExecutionStatus/)
+				echo "The status is: $status"
+				execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
+				echo "The exec status is: $execstatus"
+				if [[ $execstatus != *Passed* ]];
+				then
+				echo "Failed"
+				exit 1
+				else
+				echo "Passed"
+				exit
+				fi
+				exit */
+			}
+			stage('Security Test') {
+				steps {
+					echo 'I am running Security Test here'
+				}
+			}
+		}
+	}    
+  
 		
 	post {
   		always {
