Update Jenkinsfile_AIP

diff --git a/Jenkinsfile_AIP b/Jenkinsfile_AIP
--- a/Jenkinsfile_AIP
+++ b/Jenkinsfile_AIP
@@ -81,7 +81,7 @@ spec:
 			}
 		}
 	}
-	stage ('Stop_ESB') {
+	/* stage ('Stop_ESB') {
       steps {
         echo 'shutting down the tomcat ESB server'
        // sh 'ssh $DEPLOYMENT_USER@$DEPOYMENT_SERVER "$ESB_BIN_PATH stop || sleep 20"'
@@ -89,7 +89,7 @@ spec:
        // sh 'ssh $DEPLOYMENT_USER@$DEPOYMENT_SERVER "if [[ $(ps aux | grep /opt/mule/latest/ | grep -vc grep)  > 0 ]]; then "kill -9 $(ps -ef|pgrep -f "/opt/mule/latest/bin")"; else echo "do nothing"; fi"'
         echo 'tomcat server stopped'
       }
-    }
+    } */
     stage ('Deploy_ESB') {
       steps {
         echo 'copying the tar file from jenkins to deployment directory on app and remove the old folders and untarring the new jar and war files'
@@ -101,7 +101,7 @@ spec:
         echo 'Deployment has been completed'
       }
     }
-    stage ('Start_ESB') {
+   /* stage ('Start_ESB') {
       steps {
         echo 'starting the tomcat ESB server'
         /*sh 'ssh $DEPLOYMENT_USER@$DEPOYMENT_SERVER "$ESB_BIN_PATH start"'
@@ -109,51 +109,59 @@ spec:
         echo 'tomcat server started'
       }
 
-    } 
+    } */
     
     stage ('Smoke Test')
     {
     steps {
         echo 'Checking Worksoft status'
 	/* RESP=`curl -X GET "${bamboo.uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
-        echo "The response for current execution status is: $RESP"
-if [ "$RESP" != "[]" ];
-then
-  echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
-  exit 1
-else
-  echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
-fi
+          echo "The response for current execution status is: $RESP"
+          if [ "$RESP" != "[]" ];
+         then
+         echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
+         exit 1
+         else
+         echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
+         fi
 
-# To abort the request before attempting to re-run, uncomment and run below line.
-# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
-guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
-echo "The GUID is: $guid"
-status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-echo "The status is: $status"
-while [[ $status != *"Completed"* ]]
- do
+        # To abort the request before attempting to re-run, uncomment and run below line.
+        # abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
+        guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
+        echo "The GUID is: $guid"
+        status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+        echo "The status is: $status"
+        while [[ $status != *"Completed"* ]]
+        do
  	status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
  	echo "The status is: $status"
- sleep 15
- done
-status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
-echo "The status is: $status"
-execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
-echo "The exec status is: $execstatus"
-if [[ $execstatus != *Passed* ]];
-then
-    echo "Failed"
-    exit 1
-else
-    echo "Passed"
-    exit
-fi
-exit */
+       sleep 15
+       done
+       status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
+       echo "The status is: $status"
+       execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
+       echo "The exec status is: $execstatus"
+       if [[ $execstatus != *Passed* ]];
+           then
+              echo "Failed"
+              exit 1
+     else
+         echo "Passed"
+             exit
+      fi
+     exit */
 	echo ' Executing Smoke test '
 	exho ' Smoke test status'
 	}
      }
+     
+    stage ('Publish JavaDoc') {
+      steps {
+        echo 'Publising JavaDoc'
+       
+      }
+
+    } 
 	
 }
 }
